# Generated by Django 4.2.7 on 2023-11-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livestream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('livestream_url', models.URLField()),
                ('local_sunrise_time', models.TimeField()),
                ('local_time', models.TimeField()),
                ('weather', models.CharField(max_length=200)),
            ],
        ),
    ]
