# Generated by Django 4.2.7 on 2023-11-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alwayssunriseapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="livestream",
            name="latitude",
            field=models.DecimalField(
                decimal_places=8, default=-33.867778, max_digits=11
            ),
        ),
        migrations.AddField(
            model_name="livestream",
            name="longitude",
            field=models.DecimalField(decimal_places=8, default=151.21, max_digits=11),
        ),
    ]
