# Generated by Django 4.2.7 on 2023-11-29 00:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alwayssunriseapp", "0002_livestream_latitude_livestream_longitude"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="livestream",
            name="local_sunrise_time",
        ),
        migrations.AddField(
            model_name="livestream",
            name="local_sunrise_time_today",
            field=models.TimeField(default="06:56:44"),
        ),
        migrations.AddField(
            model_name="livestream",
            name="local_sunrise_time_tomorrow",
            field=models.TimeField(default="06:56:44"),
        ),
    ]
