# Generated by Django 4.2.7 on 2023-11-29 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alwayssunriseapp", "0004_livestream_utc_sunrise_time_today_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="livestream",
            name="timezone",
            field=models.CharField(default="Sydney/Australia", max_length=200),
        ),
    ]
