# Generated by Django 4.2.7 on 2023-11-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alwayssunriseapp", "0005_livestream_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livestream",
            name="local_sunrise_time_today",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="livestream",
            name="local_sunrise_time_tomorrow",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="livestream",
            name="local_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="livestream",
            name="timezone",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="livestream",
            name="utc_sunrise_time_today",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="livestream",
            name="utc_sunrise_time_tomorrow",
            field=models.DateTimeField(),
        ),
    ]
