# Generated by Django 4.2.7 on 2023-11-29 08:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("alwayssunriseapp", "0006_alter_livestream_local_sunrise_time_today_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="livestream",
            old_name="local_sunrise_time_today",
            new_name="sunrise_time_today",
        ),
        migrations.RenameField(
            model_name="livestream",
            old_name="local_sunrise_time_tomorrow",
            new_name="sunrise_time_tomorrow",
        ),
        migrations.RemoveField(
            model_name="livestream",
            name="utc_sunrise_time_today",
        ),
        migrations.RemoveField(
            model_name="livestream",
            name="utc_sunrise_time_tomorrow",
        ),
    ]
