# Generated by Django 4.2.7 on 2023-11-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "alwayssunriseapp",
            "0007_rename_local_sunrise_time_today_livestream_sunrise_time_today_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="livestream",
            name="local_time",
        ),
        migrations.AlterField(
            model_name="livestream",
            name="latitude",
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name="livestream",
            name="longitude",
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
    ]
