# Generated by Django 4.2.7 on 2023-12-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alwayssunriseapp", "0008_remove_livestream_local_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="livestream",
            name="livestream_url",
        ),
        migrations.AddField(
            model_name="livestream",
            name="youtube_id",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
