# Generated by Django 4.2.7 on 2023-12-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alwayssunriseapp", "0009_remove_livestream_livestream_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livestream",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=11, null=True
            ),
        ),
        migrations.AlterField(
            model_name="livestream",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=11, null=True
            ),
        ),
    ]
