# Generated by Django 4.2.7 on 2023-12-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "alwayssunriseapp",
            "0010_alter_livestream_latitude_alter_livestream_longitude",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="livestream",
            options={"ordering": ["timezone"]},
        ),
        migrations.AlterField(
            model_name="livestream",
            name="sunrise_time_today",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="livestream",
            name="sunrise_time_tomorrow",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="livestream",
            name="timezone",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="livestream",
            name="weather",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
